Temporary tweet post function
workout-engineers/triceps pull request #6
Opened 2018-06-21 10:47 UTC by ichiro-iwasaki

投稿を作成するページが完成したので、チェックおなしゃす！！

2018-06-21 13:55 UTC, ichiro-iwasaki commented
本の名前入力するところは、最終的にtweets-tableのbook_idに情報を格納する予定で、数字を入力するようになってます。

2018-06-21 15:10 UTC, kinshotomoya requested changes
すまん、各ファイルでコメントした事と、以下の4点について共有したいです！
以下の4点、このPR前に共有すればよかった。すまんねmm

1. `.rb`ファイルをcommitする前に、`bundle exec rubocop -a` をして欲しい！！これは、rubyのコードの質を保つためのgemを実行するもので、行が長すぎたり、不要な改行があったら教えてくれる！

2. htmlって、hamlやslimで書いたりしない？？？
hamlかslimで書いた方が後々開発効率は上がると思う！！ 

3. PRのdescription箇所に、デザインのスクショ欲しい！！！どんなデザインやったのか、見れた方がレビューしやすいので、お願いしたいですmmmmmm

4. 次の実装は、アカウント作成画面を作成しよか！！
ユーザーが一番最初に触れる画面から作成した方が、他のcontrollerでセッション管理とかの実装をしやすい！！！

2018-06-21 15:10 UTC, kinshotomoya commented on db/migrate/20180617044256_create_tweets.rb
> +      t.integer :book_id, foreign_key: true, comment:"bookのid"
わお、見逃してた！！！
👍

2018-06-21 15:10 UTC, kinshotomoya commented on app/controllers/tweets_controller.rb
> +  private
privateの下、一行空けよか！

2018-06-21 15:10 UTC, kinshotomoya commented on app/controllers/tweets_controller.rb
> +    Tweet.create(tweet_params)
tweetを作成したあとは、どのページに遷移するんやっけ？？
このままやったら、create.hamlに遷移するようになってるけど、どうかな？？？

2018-06-21 15:10 UTC, kinshotomoya commented on app/views/tweets/new.html.erb
> +    <%= f.text_field :book_id, placeholder: "本の名前を入力してください。", class: "tc-inputs book-name-create" %>
> 本の名前入力するところは、最終的にtweets-tableのbook_idに情報を格納する予定で、数字を入力するようになっ> てる！

これやんな？？
ここって、どんな処理の流れになる感じやっけ？？教えて欲しい！！！mm
ex) `ユーザーが本の名前を入力` -> `バックエンド側で本の名前でAPI叩く` -> .........

2018-06-22 04:33 UTC, ichiro-iwasaki commented on db/migrate/20180617044256_create_tweets.rb
> +      t.integer :book_id, foreign_key: true, comment:"bookのid"
👍

2018-06-22 04:33 UTC, ichiro-iwasaki commented on app/controllers/tweets_controller.rb
> +  private
done!

2018-06-22 04:35 UTC, ichiro-iwasaki commented on app/controllers/tweets_controller.rb
> +    Tweet.create(tweet_params)
tweet作成したら、トップページのタイムラインに戻る予定！
ただ、まだトップページが出来てないから保留しといた！

2018-06-22 04:39 UTC, ichiro-iwasaki commented on app/views/tweets/new.html.erb
> +    <%= f.text_field :book_id, placeholder: "本の名前を入力してください。", class: "tc-inputs book-name-create" %>
それそれ！
ユーザーが本の名前を入力（インクリでamazonのapiから本を選択してもらう。）
↓
本を選択し終わって、投稿がcreateされる時に、本はbooksテーブルに格納される（同じ本が既にあれば、格納はなし）
↓
本が格納されてbook_idが決まるので、tweetsテーブルにはbook_idが保存される。

みたいな感じで考えてるんやけど、amazonのapiから本の名前、（ついでにアフィリurl）を保存する機能つけてから、こっちも改造しよかなとおもてた！

2018-06-22 04:45 UTC, ichiro-iwasaki commented
1.bundle exec rubocop -a　了解っす！！！

2.erbファイルhamlに変更した！<%= %>←打つのめっちゃめんどくさー！って思ってたから助かった笑

3.　https://gyazo.com/b6399228d9f55a190a1f8665b7d908f4
　　↑投稿画面

4.なるほど！了解！！

2018-06-22 13:30 UTC, kinshotomoya commented on app/controllers/tweets_controller.rb
> +    Tweet.create(tweet_params)
なるほど！！！
コメントアウトで以下のように書いといてくれる？？？
`TODO: トップページが出来次第、renderを実装`

2018-06-22 13:35 UTC, kinshotomoya reviewed
2点、コメントしました！！！！

2018-06-22 13:35 UTC, kinshotomoya commented on app/controllers/tweets_controller.rb
> +    # .merge(user_id: params[:user_id])
不要なら消しましょか！！！

2018-06-22 13:35 UTC, kinshotomoya commented on app/views/tweets/new.html.haml
> +    = f.text_field :book_id, placeholder: "本の名前を入力してください。", class: "tc-inputs book-name-create"
ごめん結局ここって、ユーザーは本の名前を入力して、その名前をバックエンドに送る？？
って感じの仕様やっけ？？

2018-06-22 13:44 UTC, ichiro-iwasaki commented on app/controllers/tweets_controller.rb
> +    Tweet.create(tweet_params)
done!
今後、保留箇所コメントアウトで書きます！

2018-06-22 13:49 UTC, ichiro-iwasaki commented on app/controllers/tweets_controller.rb
> +    # .merge(user_id: params[:user_id])
これ、tweetテーブルにuser_id入れるために必要なんやけど、今まだユーザー登録の機能が付いてないからコメントアウトしといた。
（user_idはnull許可してないから、エラーになるはず）
コメントアウトで書いときます！

2018-06-22 14:21 UTC, ichiro-iwasaki commented on app/views/tweets/new.html.haml
> +    = f.text_field :book_id, placeholder: "本の名前を入力してください。", class: "tc-inputs book-name-create"
イメージでは、

①ユーザーが本を入力する。その時にamazonAPIが動いて、アマゾン内の本のインクリメンタルサーチが入る。
https://gyazo.com/4681ea25a76bfffbcc65386b6b2e699d
（参照：https://qiita.com/tatsuki-m/items/043f14e7d4504277c947）
このgyazoまんまみたいな、本の名前入力欄（かつ、amazon内検索欄）をつくる。

②本が決定されて、submitボタンが押される。

③ユーザーが選択した本がbooksテーブルに無い場合、その本の名前を取得してbooksテーブルの新しいレコードが作成される。そんで、できたての新しいbookレコードのidが持ってこられる。
（ユーザーが選んだ本が既にbooksテーブルにある場合、そのbookレコードのidが持ってこられる。ユーザーの選んだ本が新規か既存かは、booksテーブルのnameカラムで参照）

④持ってこられたbookのidを、tweetsテーブルのbook_idに格納する形で、tweetをcreate完了。


みたいに考えてる！
ややこしくなってごめん！^^;　分かりにくいところあったら言って！

2018-06-23 05:37 UTC, kinshotomoya commented on app/controllers/tweets_controller.rb
> +    # .merge(user_id: params[:user_id])
なるほど！！！！
コメントアウトよろしくです！mm

2018-06-23 05:43 UTC, kinshotomoya commented on app/views/tweets/new.html.haml
> +    = f.text_field :book_id, placeholder: "本の名前を入力してください。", class: "tc-inputs book-name-create"
詳しい説明ありがとう！！！
理解しました！！

入力するのは本の名前やけど、submitする際には選択された本のidをバックエンドに送るから、
`f.text_field :book_id`になってるんやね！！！！！
おっけやと思う！

2018-06-23 05:44 UTC, kinshotomoya approved these changes
LGTM

2018-06-23 05:44 UTC, kinshotomoya commented
![o061206121425546585006](https://user-images.githubusercontent.com/21333415/41806176-f0968882-76f3-11e8-9ca4-c95df5e218f0.jpg)

2018-06-23 07:07 UTC, merged