user page
workout-engineers/triceps pull request #8
Opened 2018-07-07 03:14 UTC by ichiro-iwasaki

https://gyazo.com/9e88bb3d6a18dcdb99945a153090b03a

ユーザーの詳細ページ作った！
今の所、ユーザー名を取ってきて名前のところに表示させてるだけやけど、次にツイート作成ページ作って、ユーザーのツイート一覧も表示できるようにします。

2018-07-07 15:15 UTC, kinshotomoya approved these changes
何点かコメントしました！

2018-07-07 15:15 UTC, kinshotomoya commented on app/helpers/users_helper.rb
> +module UsersHelper
helper使わんと思うから、削除しよか！！

2018-07-07 15:15 UTC, kinshotomoya commented on app/views/users/show.html.haml
> +    .content
ここって、userが保持するtweetをeachで回して表示させよ！

2018-07-07 15:15 UTC, kinshotomoya commented on config/settings.yml
> +  password: "ichiro-i0302"
このファイル gitigonreで隠そうか！

2018-07-07 15:15 UTC, kinshotomoya commented on spec/controllers/users_controller_spec.rb
> +RSpec.describe UsersController, type: :controller do
一旦、機能作り終わったらテスト書いていこうか！

2018-07-07 15:15 UTC, kinshotomoya commented on app/views/devise/sessions/new.html.haml
> +  = render "devise/shared/links"
改行しよか！

2018-07-07 15:15 UTC, kinshotomoya commented on app/assets/javascripts/user-show.js
> +});
改行しよか！

2018-07-07 15:15 UTC, kinshotomoya commented on app/assets/stylesheets/log-in.css
> +}
改行しよか！

2018-07-07 15:15 UTC, kinshotomoya commented on app/controllers/users_controller.rb
> +class UsersController < ApplicationController
一旦機能作り終えたら、エラーハンドリングしていこうか！
具体的には、findで例外が起こった時にエラー画面を出すのではなくて、メッセージを出してあげる！などなど

2018-07-07 15:16 UTC, kinshotomoya requested changes
すまん、間違えてapproveした！わら

2018-07-08 10:08 UTC, ichiro-iwasaki commented on app/helpers/users_helper.rb
> +module UsersHelper
done.
tweets_helper.rbも消しといた。

2018-07-08 14:59 UTC, ichiro-iwasaki commented on app/views/users/show.html.haml
> +    .content
done!
tweet作成機能つけてなかったから、db/seed.rbとfackerで作った！

2018-07-08 15:51 UTC, ichiro-iwasaki commented on config/settings.yml
> +  password: "ichiro-i0302"
done!

2018-07-08 15:51 UTC, ichiro-iwasaki commented on config/settings.yml
> +  password: "ichiro-i0302"
やっちまってたわw

2018-07-08 15:52 UTC, ichiro-iwasaki commented on spec/controllers/users_controller_spec.rb
> +RSpec.describe UsersController, type: :controller do
👍

2018-07-08 15:55 UTC, ichiro-iwasaki commented on app/views/devise/sessions/new.html.haml
> +  = render "devise/shared/links"
done!

2018-07-08 15:56 UTC, ichiro-iwasaki commented on app/assets/javascripts/user-show.js
> +});
done!

2018-07-08 15:58 UTC, ichiro-iwasaki commented on app/assets/stylesheets/log-in.css
> +}
done!
最後に１行余白の行を作るのが作法なん？

2018-07-08 16:04 UTC, ichiro-iwasaki commented on app/controllers/users_controller.rb
> +class UsersController < ApplicationController
了解！！
エラーハンドリング、ググってみた！！
適切なフラッシュメッセージとか、入力内容がダメな時のリダイレクトとかも考えていくわ！

2018-07-08 16:04 UTC, ichiro-iwasaki commented
approve,りょですw

2018-07-10 12:48 UTC, kinshotomoya commented on app/views/users/show.html.haml
> +    .content
いいね！！！！！！！
seed.rbは役に立つ！

2018-07-10 12:49 UTC, kinshotomoya commented on app/assets/stylesheets/log-in.css
> +}
そうらしい！！！
gitでも最後改行セーへんかったら、警告出るもんなぁ

2018-07-10 12:49 UTC, kinshotomoya commented on app/controllers/users_controller.rb
> +class UsersController < ApplicationController
いいねええ！
今度！

2018-07-10 14:08 UTC, kinshotomoya reviewed
一点だけコメントしました！

2018-07-10 14:08 UTC, kinshotomoya commented on vendor/bundle/gems/railties-5.1.6/lib/rails/generators/rails/app/templates/gitignore
> +settings.yml
これgitignore??

`triceps/.gitigonre`は存在しない？？

2018-07-10 14:27 UTC, ichiro-iwasaki commented on vendor/bundle/gems/railties-5.1.6/lib/rails/generators/rails/app/templates/gitignore
> +settings.yml
done です〜！！！

2018-07-10 14:59 UTC, kinshotomoya approved these changes
LGTM!!!!!!!!!!!!!!
![default](https://user-images.githubusercontent.com/21333415/42518620-3a043314-849d-11e8-8876-e7b6a35b2895.jpeg)

2018-07-10 15:01 UTC, merged